# Config file used by .github/workflows/labeler.yml

# This file matches file/folder changes to labels

# e.g to add the test label to any changes in the /tests directory:

# test:
#   - tests/*

ghActions:
    - .github/workflows/**/*
documentation:
    - docs/**/*
    - docs/*
    - '**/*.md'
jenkins-pipeline:
    - pipelines/**/*
    - pipelines/*
