# Config file used by .github/workflows/labeler.yml

# This file matches file/folder changes to labels. See https://github.com/actions/labeler for more information.

# e.g to add the test label to any changes in the /tests directory:

# test:
# - changed-files:
#   - tests/*

ghActions:
- changed-files:
  - .github/workflows/**/*
documentation:
- changed-files:
  - docs/**/*
  - docs/*
  - '**/*.md'
jenkins-pipeline:
- changed-files:
  - pipelines/**/*
  - pipelines/*
generation:
- changed-files:
  - pipelines/build/regeneration/*
  - pipelines/build/common/config_regeneration.groovy
docker:
- changed-files:
  - pipelines/build/dockerFiles/*
testing:
- changed-files:
  - pipelines/build/prTester/*
  - pipelines/src/test/*
code-tools:
- changed-files:
  - tools/*
gradle:
- changed-files:
  - pipelines/gradle/*
  - pipelines/build.gradle
  - pipelines/gradlew
cross-compile:
- changed-files:
  - pipelines/build/common/cross_compiled_version_out.groovy
