# Config file used by .github/workflows/labeler.yml

# This file matches issue/pr contents using regex to labels. See Multi Labeller https://github.com/marketplace/actions/multi-labeler for more information.

# e.g to add the windows label to any issue/pr with a title containing the word windows:

#   - label: "windows"
#     matcher:
#       title: "windows"

# You can also regex match body, comments, commits, authors etc:

#   - label: "feat"
#     sync: true # remove label if match failed, default: false (pull_request/issue only)
#     matcher:
#       # Matcher will match on any 7 matcher
#       title: "^feat:.*"
#       body: "/feat"
#       comment: "/feat"
#       branch: "^feat/.*"
#       commits: "^feat:.*"
#       author:
#         - github-actions
#         - fuxingloh
#       files:
#         any: [ "app/*" ]
#         all: [ "!app/config/**" ]
#         count:
#           gte: 1
#           lte: 1000

version: v1

labels:
  - label: "mac"
    matcher:
      title: "mac"
      body: "mac"
  - label: "aix"
    matcher:
      title: "aix"
      body: "aix"
  - label: "windows"
    matcher:
      title: "windows"
      body: "windows"
  - label: "solaris"
    matcher:
      title: "solaris"
      body: "solaris"
  - label: "linux"
    matcher:
      title: "linux"
      body: "linux"
  - label: "alpine-linux"
    matcher:
      title: "alpine"
      body: "alpine"
  - label: "arm"
    matcher:
      title: "arm"
      body: "arm"
  - label: "aarch"
    matcher:
      title: "aarch"
      body: "aarch"
  - label: "ppc64le"
    matcher:
      title: "ppc"
      body: "plinux"
  - label: "s390x"
    matcher:
      title: "s390"
      body: "zlinux"
  - label: "x64"
    matcher:
      title: "x64"
      body: "x64"
  - label: "sparcv9"
    matcher:
      title: "sparc"
      body: "sparc"
  - label: "hotspot"
    matcher:
      title: "hotspot"
      body: "hotspot"
  - label: "openj9"
    matcher:
      title: "j9"
      body: "j9"
  - label: "dragonwell/alibaba"
    matcher:
      title: "dragonwell"
      body: "alibaba"
  - label: "bisheng"
    matcher:
      title: "bisheng"
      body: "bisheng"
  - label: "docker"
    matcher:
      title: "docker"
      body: "docker"
  - label: "generation"
    matcher:
      title: "generat"
      body: "generat"
  - label: "testing"
    matcher:
      title: "test"
      body: "test"
  - label: "installer"
    matcher:
      title: "install"
      body: "installer"
  - label: "cross-compile"
    matcher:
      title: "cross"
      body: "risc"
  - label: "hacktoberfest"
    matcher:
      body: "hacktober"
