name: Code Freeze Bot

# Controls when the workflow will run
on:
  pull_request_target:
    branches: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  codefreeze:
    uses: adoptium/.github/.github/workflows/code-freeze.yml@main
    secrets: inherit
